---
title: Economics
---

Welcome to Economics! This course will introduce you to the basic tools that economists use to understand and explain how our diverse wants and needs are met in our modern economy. Through this semester we will learn how producers and consumers interact and how they turn scarce resources into the goods and services we want and need.

This course is intended to be interactive. We will continue to build on the concepts we learn so it is important to ask questions early before we move on to new material. You are encouraged to talk about the material in this class (including the homeworks) with your fellow students.

Please consult the syllabus first before asking questions about due dates or exams. If there are any changes over the course of the semester to our schedule it will be announced in class and posted here.

# Helpful links

[D2L](https://d2l.lonestar.edu/d2l/home)

[Spring 2018 (Online)](http://connect.mheducation.com/class/j-carrasco-spring-2018---section-5009-online)

[Spring 2018 (Hybrid)](http://connect.mheducation.com/class/j-carrasco-spring-2018---section-5011-hybrid)
