---
title: "Macroeconomics"
---

### What is Macroeconomics?

Macroeconomics is the study of the economy as a whole. It may seem like an impossible task to break down and understand the collective actions of an entire society, but it is important to face this challenge head on. We start by observing the economic phenomena in our everyday world. The jobs people have. They money they earn and spend. The price of goods and services. These measurements serve as the foundation for us to test our economic theories, simple models that help us tell the story of the economy at work.

No model is ever perfect, but we will find that even imperfect models can go a long way to explain what we observe in the real world. We use economic models to discipline our thinking. Models allow us to subject our economic intuition to the evidence. The theories that survive are the ones that do the best job of explaining the economic events we observe. Our goal as macroeconomists is to discard the theories that cannot stand up to the evidence and continually improve those that do.

Ultimately, we want to use these models as tools to help us navigate the complex economic questions that arise in our everyday lives. Questions like why even in our modern world do some countries still struggle with poverty and lack stable access to food and water? Why do even advanced economies like ours still experience economic slowdowns that can threaten jobs. Is government spending and debt a threat to our long run economic security?

### What will I learn?

Topics covered include

* Business Cycles
* Unemployment
* Inflation
* Fiscal Policy
* Monetary Policy
* Interest Rates
* Money Creation
* International Trade
* Personal Finance
